// Game phases - extracted to break circular dependency between GameContext and reducers
export const GAME_PHASE = {
  MAIN_MENU: 'main_menu',
  MAP: 'map',
  COMBAT: 'combat',
  COMBAT_REWARD: 'combat_reward',
  CARD_REWARD: 'card_reward',
  REST_SITE: 'rest_site',
  SHOP: 'shop',
  EVENT: 'event',
  GAME_OVER: 'game_over',
  VICTORY: 'victory',
  DATA_EDITOR: 'data_editor',
  CARD_SELECT_HAND: 'card_select_hand',
  CARD_SELECT_DISCARD: 'card_select_discard',
  CARD_SELECT_EXHAUST: 'card_select_exhaust'
};

// Initial game state factory
export const createInitialState = () => ({
  phase: GAME_PHASE.MAIN_MENU,
  player: {
    maxHp: 80,
    currentHp: 80,
    block: 0,
    energy: 3,
    maxEnergy: 3,
    gold: 99,
    strength: 0,
    dexterity: 0,
    vulnerable: 0,
    weak: 0,
    frail: 0,
    artifact: 0,
    intangible: 0,
    thorns: 0,
    metallicize: 0,
    platedArmor: 0,
    regen: 0,
    hex: 0,
    flight: 0,
    barricade: false,
    berserk: 0,
    brutality: false,
    combust: null,
    corruption: false,
    darkEmbrace: false,
    demonForm: 0,
    doubleTap: 0,
    evolve: 0,
    feelNoPain: 0,
    fireBreathing: 0,
    juggernaut: 0,
    rage: 0,
    rupture: 0,
    flameBarrier: 0,
    noDrawNextTurn: false,
    noDrawThisTurn: false,
    entangle: false,
    drawReduction: 0,
    pendingBlock: 0,
    penNibActive: false,
    cardsPlayedThisTurn: 0,
    attacksPlayedThisTurn: 0,
    skillsPlayedThisTurn: 0,
    powersPlayedThisTurn: 0,
    flexStrengthLoss: 0
  },
  deck: [],
  drawPile: [],
  hand: [],
  discardPile: [],
  exhaustPile: [],
  relics: [],
  potions: [null, null, null],
  enemies: [],
  currentFloor: 0,
  act: 1,
  map: null,
  currentNode: null,
  selectedCard: null,
  targetingMode: false,
  turn: 0,
  combatRewards: null,
  cardRewards: null,
  animation: null,
  message: null,
  combatLog: [],
  cardSelection: null,
  pendingCardPlay: null
});
